### ISSUE TITLE
remove the .DS_Store file in src directory

### ISSUE THREAD

**Issue by eddiejaoude** [notwaving/alexa-skill-twin-peaks-game#1]
<img width="1106" alt="screenshot 2017-10-01 21 11 46" src="https://user-images.githubusercontent.com/624760/31058533-33bb3446-a6ed-11e7-9474-c05e3d554811.png">

**Comment by notwaving** [comment]
Gone now! Thanks for having my back!

**Comment by eddiejaoude** [comment]
No problem 🤓 . I should have done a PR and it would have helped my Hactoberfest quota 😝
